INSERT INTO FM_STORM_DETAIL (ID,TYPE,RULEID,FIRST_OCCURRENCE_TIME,LAST_OCCURRENCE_TIME,OCCURRENCE_TIMES,FINISH_TIME,REASON,SMSSTATE,EVENT_SOURCE,FILTER_COUNT)
VALUES (SYS_GUID (),'·þÎñÆ÷','rid001',SYSDATE,SYSDATE,1,SYSDATE,
